apiVersion: v1
kind: Secret
metadata:
  annotations: tekton.dev/git-0=https://github.com/deimoscloud
    
  name: github-deimoscloud
  namespace: tekton-runs
type: kubernetes.io/basic-auth
stringData:
  username: siphokazi-dolo-deimos
  password: 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




