apiVersion: v2
name: prometheus-modbus-exporter
description: A Helm chart for prometheus-modbus-exporter

keywords:
  - modbus
  - modbus_exporter
  - metric
  - monitoring
  - prometheus

type: application

version: 0.1.0
appVersion: "0.4.0"

maintainers:
  - name: openenergyprojects
    email: openenergyprojects@gmail.com
