site_name: sips-cicd

repo_url: https://github.com/DeimosCloud/sips-cicd

edit_uri: edit/main/docs/
     
nav:

theme:
    name: readthedocs
    navigation_depth: 2
    features:
        - navigation.expand

markdown_extensions:
    - toc:
          permalink: True
          separator: "_"

plugins:
    - techdocs-core
