apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        argocd-image-updater.argoproj.io/container.allow-tags: regexp:^staging-(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
        argocd-image-updater.argoproj.io/container.update-strategy: latest
    name: loadgenerator
    namespace: argocd
spec:
    source:
        helm:
            valueFiles:
                - ../../environments/overlays/staging/loadgenerator-values.yaml
