name: $(Build.BuildId)_$(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:rr)

trigger:
  branches:
    include:
    - demo
  paths:
    #exclude:
    include:
    - src/node-web-app
    - src/node-web-app/demo-app
    - pipelines/webapp.demo.yaml

pool:
  name: "managed-infra-demo"

resources:
  repositories:
  - repository: ado-pipeline-blueprints
    name: foundational-blueprints-pipelines/ado-pipeline-blueprints
    type: git

stages:
- stage: build
  dependsOn: []
  variables: 
  - group: managed_infra_demo_base_image_variable_group
  jobs:
  - job: container
    steps:
    - template: /pipelines/steps-build-and-push-generic.yaml@ado-pipeline-blueprints
      parameters:
        registry: $(registry) 
        repository: $(repository)
        imageName: demo-node-web-app
        imageTag: $(Build.SourceBranchName)-0.0.$(Build.BuildId)
        dockerFile: Dockerfile
        dockerDirectory: src/node-web-app
