apiVersion: v2
name: prometheus-ipmi-exporter
description: This is an IPMI exporter for Prometheus.

type: application

version: 0.1.0

appVersion: "1.6.1"

keywords:
  - metrics
  - ipmi
  - monitoring

home: https://github.com/prometheus-community/ipmi_exporter

maintainers:
  - name: lexfrei
    email: f@lex.la
