apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    deimos.io/environment-local: deploy
  name: podtato-head
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sips-cicd-project
  source:
    repoURL: https://github.com/DeimosCloud/sips-cicd.git
    path: src/podtato-head/delivery/chart
    targetRevision: HEAD
    helm:
      releaseName: podtatohead
      values: |
        fullnameOverride: podtatohead
        image:
          repository: localhost:5000/podtatohead
          tag: latest
        livenessProbe: {}
        podAnnotations:
            instrumentation.opentelemetry.io/inject-sdk: observability/instrumentation
        readinessProbe: {}
        service:
          port: 9090
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1